name: publish

on:
  release:
    types: [published]

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v2.3.1
      with:
        python-version: "3.x"
    - uses: snok/install-poetry@v1.3
      with:
        virtualenvs-create: true
    - name: Build the package
      run: poetry build -vvv
    - name: Publish to PyPI
      run: poetry publish --username __token__ --password ${{ secrets.pypi_token }}
      working-directory: ${{ github.workspace }}
